config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root to: 'home#index'

  resources :users, only: [:show, :edit, :update]

  resources :posts, only: [:new, :create, :show, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  validates :image, presence: true
  paginates_per 5
  # blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..10.megabytes }, 
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy

  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.order(created_at: :desc).page(params[:page])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params) 
    if @post.save
      flash[:notice] = "Your post has been uploaded"
      redirect_to root_path
    else 
      flash[:notice] = "Please attach a picture"
      redirect_to new_post_path
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to user_path(current_user)
  end

  private

  def post_params
    params.require(:post).permit(:caption, :image, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user  = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    current_user.update(user_params)
    redirect_to current_user
  end

  private 

  def user_params
    params.require(:user).permit(:username, :name, :website, :bio, :email, :phone, :gender, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>

<div class="posts">

  <% @posts.each do |post| %>
    <section class="post">
    <div class="user">
    <div class="avatar">
      <% if post.user.avatar.attached? %>
        <%= link_to user_path(post.user) do %> 
        <img src="<%= url_for(post.user.avatar) %>"/>
        <% end %>
      <% end %>
    </div>
    <div class="username">
    <%= link_to user_path(post.user) do %>
      <%= post.user.username %>
      <% end %>
    </div>
  </div>
  <img class='main-image' src="<%=(url_for(post.image))%>"/> 
  <div class="caption">
    <%= post.caption %>
  </div>
    </section>
  <% end %>
</div>
<div class='pagination'>
<%= paginate @posts %>
<div>

<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photogram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-light bg-light d-flex">
      <div class="container">
        <div class="logo">
          <a class="navbar-brand" href="/">
            <%= fa_stacked_icon "camera inverse", base: "circle"%>
            Photogram
          </a>
        </div>
        <div class="m-auto">
          <form class="form-inline search-form">
            <input class="form-control mr-sm-2" type="search" placeholder="@search" aria-label="Search">
          </form>
        </div>
        <div class="top-right-user-nav">
          <a href='/'><i class="fa fa-home"></i></a>
            <% if user_signed_in? %>
                <a><i class="fa fa-paper-plane"></i></a>
                <a><i class="fa fa-compass"></i></a>
                <a><i class="fa fa-heart"></i></a>
                <a class='new-post' href="<%= new_post_path %>"><i class="fa fa-plus"></i></a>
               <a class='user-icon' href=<%= user_path(current_user)%>>
                <i class="fa fa-user"></i>
               </a>
               <a class = 'sign-out' href="<%= destroy_user_session_path%>" data-method="delete">
                  <i class="fa fa-sign-out"></i>
                </a>
            <% else %>
              <a class= 'sign-in' href="<%= new_user_session_path%>">
                <i class="fa fa-sign-in"></i>
              </a> You are not logged in.
            <% end %>
        </div>
      </div>
    </nav>

    <main class="container" style="min-height: 500px;">
    <p class="flash-notice"><%= flash[:notice] %></p>
      <%= yield %>
    </main>

    <footer class="container footer">
      <nav class="navbar d-flex">
        <ul>
          <li>ABOUT US
          </li>
          <li>SUPPORT</li>
          <li>PRESS</li>
          <li>API</li>
          <li>JOBS</li>
          <li>PRIVACY</li>
          <li>TERMS</li>
          <li>DIRECTORY</li>
          <li>PROFILES</li>
          <li>HASHTAGS</li>
          <li>LANGUAGE</li>
        </ul>
        <p> © 2021 PHOTOGRAM </p>
      </nav>
    </footer>
  </body>
</html>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.text_field :caption %>
    <%= f.label :caption%>
  </div>
  <div class="form-group">
    <%= f.file_field :image %>
    <%= f.label :image %>
  </div>
  <div class="form-group">
    <%= f.text_field :user_id, value: current_user.id, class:'d-none'%>
  </div>
  <br>
  <div class="text-center">
    <%= f.submit 'Create Post', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="post-show row">
  <div class="col-md-9">
    <img class='main-image' src="<%=(url_for(@post.image))%>"/> 
        <div class="caption">
      <%= @post.caption %>
    </div>
  </div>
  <div class="col-md-4">
    <div class="user">
      <div class="avatar">
        <% if @post.user.avatar.attached? %>
          <%= link_to user_path(@post.user) do %>
            <img src="<%= url_for(current_user.avatar) %>"/>
          <% end %>
        <% end %>
      </div>
      <%= link_to @post.user.username, user_path(@post.user), class: 'username' %>
    </div>
  </div>
  <div class="delete">
  <% if current_user.posts.exists?(@post.id) %>
    <%= link_to 'Remove', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>
</div>

app/views/users/edit.html.erb
<div class="user-edit-page">
  <div class="actions">
    <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" data-toggle="pill" href="#v-pills-home" role="tab" aria-selected="true">Edit Profile</a>
      <a class="nav-link" data-toggle="pill">Change Password</a>
      <a class="nav-link" data-toggle="pill">Authorized Applications</a>
      <a class="nav-link" data-toggle="pill">Email and SMS</a>
      <a class="nav-link" data-toggle="pill">Manage Contacts</a>
      <a class="nav-link" data-toggle="pill">Privacy and Security</a>
    </div>
  </div>
  <div class="details tab-content">
    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
    <%= form_with model: current_user, local: true, html: {class: "form-horizontal form-edit-user"} do |f| %>
      <div class="form-group row">
        <div class="col-sm-3 col-form-label">
          <% if current_user.avatar.attached? %>
            <%= image_tag current_user.avatar, class: 'avatar' %>
          <%end %>
        </div>
        <div class="col-sm-9">
          <p class="username"><%=current_user.username %></p>
          <p class="change-photo">Change Profile Photo</p>
        </div>
        </div>
        <div class="form-group row">
          <%= f.label :avatar, class: 'col-sm-3 col-form-label' %>
        <div class="col-sm-9">
          <%= f.file_field :avatar, class: 'form-control' %>
        </div>
        </div>
  <div class="form-group row">
    <%= f.label :name, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :username, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :username, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :website, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :website, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :bio, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_area :bio, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :email, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :email, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :phone, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :phone, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :gender, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :gender, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-3">
    </div>
    <div class="col-sm-9">
      <%= f.submit "Submit", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="profile row">
    <div class="col-md-4 avatar">
      <div class="wrapper">
          <% if current_user.avatar.attached? %>
            <img src="<%= url_for(@user.avatar) %>"/>
          <%end %>
      </div>
    </div>
    
    <div class="col-md-8 basic-info">
      <div class="user-wrapper">
        <h2 class="username"><%= @user.username%></h2>
        <a class="edit-profile" href="<%= edit_user_path(current_user) %>">
          <button>Edit Profile</button>
        </a>
      </div>
      <ul class="posts">
        <li><span><%=@user.posts.count%></span> posts</li>
        <li><span>200</span> followers</li>
        <li><span>300</span> following</li>
      </ul>
      <h2 class="name"><%= @user.name %></h2>
      <h2 class="name"><%= @user.bio %></h2>
      <a class="website"><%= @user.website %></a>
    </div>
  </div>
</div>

<div class="user-tabs">
  <a class="tab active" href="">
    <i class="fa fa-th"></i>
    POSTS
  </a>
  <a class="tab" href="">
    <i class="fa fa-tv"></i>
    IGTV
  </a>
  <a class="tab" href="">
    <i class="fa fa-bookmark"></i>
    SAVED
  </a>
  <a class="tab" href="">
    <i class="fa fa-tag"></i>
    TAGGED
  </a>
</div>

<div class="user-images">
 <% @posts.each do |post|%>
    <div class="wrapper">
    <%=link_to post_path(post) do %>
      <img src="<%=(url_for(post.image))%>"/> 
    <%end%>
    </div>
  <% end %>
</div>